# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 16:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(error_messages={'required': '\xbfCu\xe1l es el nombre de la marca?'}, max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Ingrese solo letras.', regex=b'^[A-Za-z\xe1\xe9\xed\xf3\xfa\xc1\xc9\xcd\xd3\xda\\s]+$')])),
            ],
            options={
                'ordering': ['nombre'],
                'db_table': 'marcas',
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_referencia', models.CharField(error_messages={'required': '\xbfCu\xe1l es el id del producto?'}, max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='El formato del ID no es v\xe1lido', regex=b'^[A-Za-z0-9]{6}$')])),
                ('nombre', models.CharField(error_messages={'required': '\xbfCu\xe1l es el nombre del producto?s'}, max_length=40, validators=[django.core.validators.RegexValidator(message='Ingrese solo caracteres alfanumericos', regex=b'^[A-Za-z0-9]+$')])),
                ('genero', models.CharField(error_messages={'required': '\xbfCu\xe1l es el g\xe9nero?'}, max_length=6, validators=[django.core.validators.RegexValidator(message='El g\xe9nero no es v\xe1lido.', regex=b'^hombre|mujer|unisex$')])),
                ('estilo', models.CharField(error_messages={'required': '\xbfCu\xe1l es el estilo?'}, max_length=9, validators=[django.core.validators.RegexValidator(message='El estilo no es v\xe1lido', regex=b'^deportivo|formal$')])),
                ('talla', models.CharField(error_messages={'required': '\xbfCu\xe1l es la talla?'}, max_length=2, validators=[django.core.validators.RegexValidator(message='El n\xfamero de tall no es v\xe1lido', regex=b'^[27-43]$')])),
                ('stock', models.PositiveSmallIntegerField(error_messages={'required': '\xbfCuantos hay en el inventario?'}, validators=[django.core.validators.RegexValidator(message='Ingrese solo n\xfameros.', regex=b'^d+$')])),
                ('precio', models.IntegerField(error_messages={'required': 'Cu\xe1l es el precio del producto?'}, validators=[django.core.validators.RegexValidator(message='Ingrese solo n\xfameros.', regex=b'^d+$')])),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto.Marca')),
            ],
            options={
                'ordering': ['nombre'],
                'db_table': 'productos',
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
    ]
