# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 18:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20170424_0207'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField(error_messages={'required': '\xbfCuantos productos se van a comprar?'}, validators=[django.core.validators.RegexValidator(message='Ingrese solo n\xfameros.', regex=b'^d+$')])),
                ('valor', models.PositiveIntegerField(error_messages={'required': '\xbfCu\xe1l es el valor del producto(s)?'}, validators=[django.core.validators.RegexValidator(message='Ingrese solo n\xfameros.', regex=b'^d+$')])),
            ],
            options={
                'db_table': 'detalle_facturas',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('total_pagar', models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(message='Ingrese solo n\xfameros.', regex=b'^d+$')])),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.Cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.Usuario')),
            ],
            options={
                'ordering': ['-fecha'],
                'db_table': 'facturas',
                'verbose_name': 'factura',
                'verbose_name_plural': 'facturas',
            },
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto.Factura'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto.Producto'),
        ),
        migrations.AlterUniqueTogether(
            name='detallefactura',
            unique_together=set([('factura', 'producto')]),
        ),
    ]
