# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20170507_0910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='tallas',
            new_name='talla',
        ),
    ]
