# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 19:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20170427_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estilo',
            field=models.CharField(choices=[('deportivo', 'deportivo'), ('formal', 'formal')], error_messages={'required': '\xbfCu\xe1l es el estilo?'}, max_length=9, validators=[django.core.validators.RegexValidator(message='El estilo no es v\xe1lido', regex=b'^deportivo|formal$')]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='genero',
            field=models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer'), ('unisex', 'Unisex')], error_messages={'required': '\xbfCu\xe1l es el g\xe9nero?'}, max_length=6, validators=[django.core.validators.RegexValidator(message='El g\xe9nero no es v\xe1lido.', regex=b'^hombre|mujer|unisex$')]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='talla',
            field=models.CharField(choices=[('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43')], error_messages={'required': '\xbfCu\xe1l es la talla?'}, max_length=2, validators=[django.core.validators.RegexValidator(message='El n\xfamero de tall no es v\xe1lido', regex=b'^[27-43]$')]),
        ),
    ]
