# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 05:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20170427_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.PositiveIntegerField(error_messages={'required': 'Cu\xe1l es el precio del producto?'}, validators=[django.core.validators.RegexValidator(message='Ingrese solo n\xfameros.', regex=b'^d+$')]),
        ),
    ]
