# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_auto_20170428_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='TallaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'tallas_productos',
            },
        ),
        migrations.RemoveField(
            model_name='producto',
            name='talla',
        ),
        migrations.AddField(
            model_name='tallaproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Producto'),
        ),
        migrations.AddField(
            model_name='tallaproducto',
            name='talla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Talla'),
        ),
    ]
