# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0008_auto_20170428_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='talla',
            new_name='tallas',
        ),
    ]
