# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0009_auto_20170428_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallefactura',
            old_name='valor',
            new_name='total',
        ),
    ]
