# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 04:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('vendedor', 'Vendedor')], error_messages={'required': '\xbfC\xfaal es el rol del usuario?'}, max_length=13, validators=[django.core.validators.RegexValidator(message='El rol no es v\xe1lido', regex=b'^(administrador|vendedor)$')]),
        ),
    ]
