# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('es_administrador', 'es administrador'), ('es_vendedor', 'es vendedor')]},
        ),
    ]
