# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 07:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20170423_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='nombre',
            field=models.CharField(error_messages={'required': '\xbfCu\xe1l es el nombre de la Ciudad?'}, max_length=30, validators=[django.core.validators.RegexValidator(message='Ingrese solo letras.', regex=b'^[A-Za-z\xe1\xe9\xed\xf3\xfa\xc1\xc9\xcd\xd3\xda\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(error_messages={'required': '\xbfCu\xe1l es tu apellido?'}, max_length=50, validators=[django.core.validators.RegexValidator(message='Ingrese solo letras.', regex=b'^[A-Za-z\xe1\xe9\xed\xf3\xfa\xc1\xc9\xcd\xd3\xda\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(error_messages={'required': '\xbfCu\xe1l es el n\xfamero de c\xe9dula?'}, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Solo se admiten n\xfameros.', regex=b'^[0-9]+{10,10}$')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombres',
            field=models.CharField(error_messages={'required': '\xbfCu\xe1l es tu nombre?'}, max_length=50, validators=[django.core.validators.RegexValidator(message='Ingrese solo letras.', regex=b'^[A-Za-z\xe1\xe9\xed\xf3\xfa\xc1\xc9\xcd\xd3\xda\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(error_messages={'required': '\xbfCu\xe1l es el t\xe9lefono?'}, max_length=10, validators=[django.core.validators.RegexValidator(message='El n\xfamero ingresado no es v\xe1lido.', regex=b'([3]([0][0-5]|[1][0-9]|[2][0-2]|[5][01])[\\d]{7})|([2-8][\\d]{6,6})$')]),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(error_messages={'required': '\xbfCu\xe1l es el nombre del Departamento?'}, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Ingrese solo letras.', regex=b'^[A-Za-z\xe1\xe9\xed\xf3\xfa\xc1\xc9\xcd\xd3\xda\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(error_messages={'required': '\xbfCu\xe1l es tu apellido?'}, max_length=50, validators=[django.core.validators.RegexValidator(message='Ingrese solo letras.', regex=b'^[A-Za-z\xe1\xe9\xed\xf3\xfa\xc1\xc9\xcd\xd3\xda\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(error_messages={'required': '\xbfCu\xe1l es tu nombre?'}, max_length=50, validators=[django.core.validators.RegexValidator(message='Ingrese solo letras.', regex=b'^[A-Za-z\xe1\xe9\xed\xf3\xfa\xc1\xc9\xcd\xd3\xda\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('vendedor', 'Vendedor')], error_messages={'required': '\xbfCu\xe1l es el rol del usuario?'}, max_length=13, validators=[django.core.validators.RegexValidator(message='El rol no es v\xe1lido', regex=b'^(administrador|vendedor)$')]),
        ),
    ]
