# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 21:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20170424_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(error_messages={'required': '\xbfCu\xe1l es el n\xfamero de c\xe9dula?'}, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Solo se admiten n\xfameros.', regex=b'^[0-9]{10}$')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(error_messages={'required': '\xbfD\xf3nde vives?'}, max_length=80, validators=[django.core.validators.RegexValidator(message='El formato de la direcci\xf3n no es v\xe1lido.', regex=b'^[a-zA-Z0-9#\\-\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(error_messages={'required': '\xbfCu\xe1l es el t\xe9lefono?'}, max_length=10, validators=[django.core.validators.RegexValidator(message='El n\xfamero de tel\xe9fono no es v\xe1lido.', regex=b'^([3]([0][0-5]|[1][0-9]|[2][0-2]|[5][01])[\\d]{7})|([2-8][\\d]{6})$')]),
        ),
    ]
