# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_auto_20170429_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(error_messages={'required': '\xbfCu\xe1l es el t\xe9lefono?'}, max_length=10),
        ),
    ]
